export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_CLEAR_ITEMS = 'CART_RESET';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const CART_DETAILS_REQUEST = 'CART_DETAILS_REQUEST';
export const CART_DETAILS_SUCCESS = 'CART_DETAILS_SUCCESS';
export const CART_DETAILS_FAIL = 'CART_DETAILS_FAIL';

export const CART_LIST_REQUEST = 'CART_LIST_REQUEST';
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS';
export const CART_LIST_FAIL = 'CART_LIST_FAIL';

export const CART_UPDATE_REQUEST = 'CART_UPDATE_REQUEST';
export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
export const CART_UPDATE_FAIL = 'CART_UPDATE_FAIL';

export const CART_REMOVE_REQUEST = 'CART_REMOVE_REQUEST';
export const CART_REMOVE_SUCCESS = 'CART_REMOVE_SUCCESS';

export const DISCOUNT_REMOVE_REQUEST = 'DISCOUNT_REMOVE_REQUEST';
export const DISCOUNT_REMOVE_SUCCESS = 'DISCOUNT_REMOVE_SUCCESS';
export const DISCOUNT_REMOVE_FAIL = 'DISCOUNT_REMOVE_FAIL';

export const OVERALL_UPDATE_REQUEST = 'OVERALL_UPDATE_REQUEST';
export const OVERALL_UPDATE_SUCCESS = 'OVERALL_UPDATE_SUCCESS';
