export const LINE_LIST_REQUEST = 'LINE_LIST_REQUEST'
export const LINE_LIST_SUCCESS = 'LINE_LIST_SUCCESS'
export const LINE_LIST_FAIL = 'LINE_LIST_FAIL'

export const SESSION_CREATE_REQUEST = 'SESSION_CREATE_REQUEST'
export const SESSION_CREATE_SUCCESS = 'SESSION_CREATE_SUCCESS'
export const SESSION_CREATE_FAIL = 'SESSION_CREATE_FAIL'

export const SESSION_DETAILS_REQUEST = 'SESSION_DETAILS_REQUEST'
export const SESSION_DETAILS_SUCCESS = 'SESSION_DETAILS_SUCCESS'
export const SESSION_DETAILS_FAIL = 'SESSION_DETAILS_FAIL'